[project]
name = "thesis"
version = "0.1.0"
description = "Code for bachelor thesis"
authors = [{ name = "Colin Kubon" }]
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "accelerate>=1.13.0",
    "bitsandbytes>=0.49.0",
    "matplotlib>=3.10.0",
    "numpy>=2.4.0",
    "opacus>=1.6.0",
    "pandas>=3.0.0",
    "pillow>=12.1.0",
    "requests>=2.33.0",
    "sentencepiece>=0.2.0",
    "transformers>=5.5.0",
    "tqdm>=4.68.0",
    "scikit-learn>=1.9.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
cuda = [
    "torch==2.11.0+cu128",
    "torchvision==0.26.0+cu128"
]
rocm = [
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "triton-rocm>=3.6.0"
]
qt5 = [
    "PyQt5>=5.15.0"
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
conflicts = [
    [
        { extra = "cuda" },
        { extra = "rocm" },
    ]
]

[tool.uv.sources]
torch = [
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pytorch-cuda", extra = "cuda" },
]
torchvision = [
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pytorch-cuda", extra = "cuda" },
]
triton-rocm = [
    { index = "pytorch-rocm", extra = "rocm" },
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
